<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="NSScripts\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Link>Scripts\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="NSScripts\NS_Get_Helpers.cs" />
	  <Compile Remove="NSScripts\NS_Get_Location.cs" />
	  <Compile Remove="NSScripts\NS_Get_WMS_Employee.cs" />
	  <Compile Remove="NSScripts\NS_IF_Get_Items.cs" />
	  <Compile Remove="NSScripts\NS_InventoryCounting_Get_Started.cs" />
	  <Compile Remove="NSScripts\NS_Item_Get_Barcodes.cs" />
	  <Compile Remove="NSScripts\NS_TransferOrder_Get_Items.cs" />
	  <Compile Remove="NSScripts\NS_TransferOrder_Get_PendingReceipt.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="NSScripts\NS_Get_Helpers.cs" />
	  <Content Remove="NSScripts\NS_Get_Location.cs" />
	  <Content Remove="NSScripts\NS_IF_Get_Items.cs" />
	  <Content Remove="NSScripts\NS_InventoryCounting_Get_Started.cs" />
	  <Content Remove="NSScripts\NS_Item_Get_Barcodes.cs" />
	  <Content Remove="NSScripts\NS_TransferOrder_Get_Items.cs" />
	  <Content Remove="NSScripts\NS_TransferOrder_Get_PendingReceipt.cs" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Application.DataTransferObjects\Application.DataTransferObjects.csproj" />
    <ProjectReference Include="..\Application.UseCases\Application.UseCases.csproj" />
    <ProjectReference Include="..\Database.Libraries\Database.Libraries.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <Content Update="NSScripts\NS_Get_Locations.sql" Link="Scripts\NS_Get_Locations.sql" />
    <Content Update="NSScripts\NS_Location_Get_Bins.sql" Link="Scripts\NS_Location_Get_Bins.sql" />
    <Content Update="NSScripts\NS_PurchaseOrder_GetAll.sql" Link="Scripts\NS_PurchaseOrder_Get_Pending.sql" />
    <Content Update="NSScripts\NS_PurchaseOrder_Get_PendingReceipt.sql" Link="Scripts\NS_PurchaseOrder_Get_PendingReceipt.sql" />
    <Content Update="NSScripts\NS_TO_Get_Itemfulfillment_Items.sql" Link="Scripts\NS_TO_Get_Itemfulfillment_Items.sql" />
    <Content Update="NSScripts\NS_TO_x_Itemfulfillment_Get_PendingFulfillment.sql" Link="Scripts\NS_TO_Get_Itemfulfillments.sql" />
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
