<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Transactions\Receiving\ItemReceiptTransformPayload.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain.Entities\Domain.Entities.csproj" />
    <ProjectReference Include="..\Shared.Libraries\Shared.Libraries.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Transactions\TripTicket\NS\Request\" />
    <Folder Include="Transactions\Packing\Return\" />
    <Folder Include="Transactions\Packing\VRA\" />
  </ItemGroup>

</Project>
