// <auto-generated />
using System;
using Database.MsSql.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.MsSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406092429_[APHI.WMS]InventoryCountingISBN")]
    partial class APHIWMSInventoryCountingISBN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SN_OUSR")
                .StartsAt(0L);

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.LoginDEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("USR2", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.UserDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_OUSR");

                    b.HasIndex("RoleId");

                    b.ToTable("OUSR", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.UserPermissionDEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ModulePermission")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USR3", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Role.RoleDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_OROL");

                    b.ToTable("OROL", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Role.RolePermissionDEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ModulePermission")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ROL1", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Entities.Transaction.InventoryCounting.InventoryCountingDocumentDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CountingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CycleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_OICD");

                    b.ToTable("OICD", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.System.DocumentNumberDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ODCN");

                    b.HasIndex("DocumentTypeId")
                        .IsUnique();

                    b.ToTable("ODCN", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.System.ModuleDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NavRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Root")
                        .HasColumnType("bit");

                    b.Property<bool>("Transactional")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_OMDL");

                    b.HasIndex("NavRouteId");

                    b.ToTable("OMDL", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.System.ModulePermissionDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleReference")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_OMPR");

                    b.ToTable("OMPR", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.System.NavigationRouteDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("Protected")
                        .HasColumnType("bit");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ONRT");

                    b.ToTable("ONRT", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Transaction.Common.DocumentTypeDEM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ODCT");

                    b.ToTable("ODCT", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.LoginDEM", b =>
                {
                    b.HasOne("Domain.Entities.Administration.User.Management.UserDEM", null)
                        .WithMany("LoginHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.UserDEM", b =>
                {
                    b.HasOne("Domain.Entities.Administration.User.Role.RoleDEM", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Others.EmailVO", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserDEMId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("UserDEMId");

                            b1.ToTable("OUSR");

                            b1.WithOwner()
                                .HasForeignKey("UserDEMId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Others.PersonNameVO", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserDEMId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("UserDEMId");

                            b1.ToTable("OUSR");

                            b1.WithOwner()
                                .HasForeignKey("UserDEMId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Others.AccountVO", "Account", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("HashedPassword")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Locked")
                                .HasColumnType("bit");

                            b1.Property<bool>("LockoutEnabled")
                                .HasColumnType("bit");

                            b1.HasKey("UserId");

                            b1.ToTable("USR1", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("Domain.ValueObjects.Others.UserNameVO", "UserName", b2 =>
                                {
                                    b2.Property<Guid>("AccountVOUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AccountVOUserId");

                                    b2.ToTable("USR1");

                                    b2.WithOwner()
                                        .HasForeignKey("AccountVOUserId");
                                });

                            b1.Navigation("UserName")
                                .IsRequired();
                        });

                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.UserPermissionDEM", b =>
                {
                    b.HasOne("Domain.Entities.Administration.User.Management.UserDEM", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Role.RolePermissionDEM", b =>
                {
                    b.HasOne("Domain.Entities.Administration.User.Role.RoleDEM", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Entities.Transaction.InventoryCounting.InventoryCountingDocumentDEM", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Transaction.AppDocNumVO", "LsmsDocNum", b1 =>
                        {
                            b1.Property<Guid>("InventoryCountingDocumentDEMId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LsmsDocNum");

                            b1.HasKey("InventoryCountingDocumentDEMId");

                            b1.ToTable("OICD");

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountingDocumentDEMId");
                        });

                    b.OwnsOne("Domain.Entities.ValueObjects.Others.WarehouseVO", "Warehouse", b1 =>
                        {
                            b1.Property<Guid>("InventoryCountingDocumentDEMId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("WhsCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("WhsCode");

                            b1.Property<string>("WhsName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("WhsName");

                            b1.HasKey("InventoryCountingDocumentDEMId");

                            b1.ToTable("OICD");

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountingDocumentDEMId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Transaction.SapDocumentReferenceVO", "SapReference", b1 =>
                        {
                            b1.Property<Guid>("InventoryCountingDocumentDEMId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("BaseDocEntry")
                                .HasColumnType("int")
                                .HasColumnName("SapBaseDocEntry");

                            b1.Property<int?>("BaseDocNum")
                                .HasColumnType("int")
                                .HasColumnName("SapBaseDocNum");

                            b1.Property<int?>("DocEntry")
                                .HasColumnType("int")
                                .HasColumnName("SapDocEntry");

                            b1.Property<int?>("DocNum")
                                .HasColumnType("int")
                                .HasColumnName("SapDocNum");

                            b1.HasKey("InventoryCountingDocumentDEMId");

                            b1.ToTable("OICD");

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountingDocumentDEMId");
                        });

                    b.OwnsMany("Domain.Entities.ValueObjects.Transaction.InventoryCountingDocumentLineVO", "DocumentLines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("ActualQuantity")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("ISBN")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ISBN");

                            b1.Property<Guid>("InventoryCountingDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("UoMCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("UoMName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<decimal>("UoMValue")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("InventoryCountingDocumentId");

                            b1.ToTable("ICD1", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountingDocumentId");
                        });

                    b.OwnsMany("Domain.Entities.ValueObjects.Transaction.InventoryCountingSheetVO", "Sheets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CounterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("InventoryCountingDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("SubmittedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("InventoryCountingDocumentId");

                            b1.ToTable("ICD2", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InventoryCountingDocumentId");

                            b1.OwnsMany("Domain.Entities.ValueObjects.Transaction.InventoryCountingSheetLineVO", "SheetLines", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("InventoryCountingSheetVOId")
                                        .HasColumnType("int");

                                    b2.Property<string>("ItemCode")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("ItemName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<decimal>("Quantity")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("SheetNo")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("UoMCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("UoMName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<decimal>("UoMValue")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("InventoryCountingSheetVOId");

                                    b2.ToTable("ICD3", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryCountingSheetVOId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Transaction.AppDocNumVO", "SheetNo", b2 =>
                                {
                                    b2.Property<int>("InventoryCountingSheetVOId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("SheetNo");

                                    b2.HasKey("InventoryCountingSheetVOId");

                                    b2.ToTable("ICD2");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryCountingSheetVOId");
                                });

                            b1.Navigation("SheetLines");

                            b1.Navigation("SheetNo")
                                .IsRequired();
                        });

                    b.Navigation("DocumentLines");

                    b.Navigation("LsmsDocNum")
                        .IsRequired();

                    b.Navigation("SapReference");

                    b.Navigation("Sheets");

                    b.Navigation("Warehouse")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.System.DocumentNumberDEM", b =>
                {
                    b.HasOne("Domain.Entities.Transaction.Common.DocumentTypeDEM", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.System.DocumentNumberDEM", "DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ODCN_ODCT");
                });

            modelBuilder.Entity("Domain.Entities.System.ModuleDEM", b =>
                {
                    b.HasOne("Domain.Entities.System.NavigationRouteDEM", null)
                        .WithMany()
                        .HasForeignKey("NavRouteId");

                    b.OwnsMany("Domain.ValueObjects.Others.PermissionVO", "ModulePermissions", b1 =>
                        {
                            b1.Property<Guid>("ModuleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Permission");

                            b1.HasKey("ModuleId", "Id");

                            b1.ToTable("MDL1", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModuleId");
                        });

                    b.Navigation("ModulePermissions");
                });

            modelBuilder.Entity("Domain.Entities.System.ModulePermissionDEM", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Others.PermissionVO", "Permission", b1 =>
                        {
                            b1.Property<Guid>("ModulePermissionDEMId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Permission");

                            b1.HasKey("ModulePermissionDEMId");

                            b1.ToTable("OMPR");

                            b1.WithOwner()
                                .HasForeignKey("ModulePermissionDEMId");
                        });

                    b.Navigation("Permission")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Management.UserDEM", b =>
                {
                    b.Navigation("LoginHistory");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.Administration.User.Role.RoleDEM", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
